packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  - 'templates/**'
  - 'apps/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
options:
  prefer-workspace-packages: true