/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import * as React, { useRef } from "solid-js";
import { useAnimations, useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Wolf3D_Avatar: THREE.SkinnedMesh;
    Hips: THREE.Bone;
  };
  materials: {
    Wolf3D_Avatar: THREE.MeshStandardMaterial;
  };
};

type ActionName = "Armature|mixamo.com|Layer0";
interface GLTFActions extends THREE.AnimationClip {
  name: ActionName;
}

export default function PlayerModel(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/character.glb") as GLTFResult;
  const { animations } = useGLTF("/animations.glb") as GLTF & {
    animations: GLTFActions[];
  };

  const { actions } = useAnimations<GLTFActions>(animations, group);

  React.useLayoutEffect(
    () => void actions["Armature|mixamo.com|Layer0"]?.play(),
    []
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" userData={{ name: "Armature" }}>
          <primitive object={nodes.Hips} />
          <skinnedMesh
            name="Wolf3D_Avatar"
            geometry={nodes.Wolf3D_Avatar.geometry}
            material={materials.Wolf3D_Avatar}
            skeleton={nodes.Wolf3D_Avatar.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Avatar.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Avatar.morphTargetInfluences}
            userData={{
              targetNames: [
                "mouthOpen",
                "mouthSmile",
                "eyesClosed",
                "eyesLookUp",
                "eyesLookDown",
                "eyeBlinkLeft",
                "eyeSquintLeft",
                "eyeWideLeft",
                "eyeBlinkRight",
                "eyeSquintRight",
                "eyeWideRight",
                "jawForward",
                "jawLeft",
                "jawRight",
                "jawOpen",
                "mouthClose",
                "mouthFunnel",
                "mouthPucker",
                "mouthLeft",
                "mouthRight",
                "mouthSmileLeft",
                "mouthSmileRight",
                "mouthFrownLeft",
                "mouthFrownRight",
                "mouthDimpleLeft",
                "mouthDimpleRight",
                "mouthStretchLeft",
                "mouthStretchRight",
                "mouthRollLower",
                "mouthRollUpper",
                "mouthShrugLower",
                "mouthShrugUpper",
                "mouthPressLeft",
                "mouthPressRight",
                "mouthLowerDownLeft",
                "mouthLowerDownRight",
                "mouthUpperUpLeft",
                "mouthUpperUpRight",
                "browDownLeft",
                "browDownRight",
                "browInnerUp",
                "browOuterUpLeft",
                "browOuterUpRight",
                "cheekPuff",
                "cheekSquintLeft",
                "cheekSquintRight",
                "noseSneerLeft",
                "noseSneerRight",
                "viseme_sil",
                "viseme_PP",
                "viseme_FF",
                "viseme_TH",
                "viseme_DD",
                "viseme_kk",
                "viseme_CH",
                "viseme_SS",
                "viseme_nn",
                "viseme_RR",
                "viseme_aa",
                "viseme_E",
                "viseme_I",
                "viseme_O",
                "viseme_U",
              ],
              name: "Wolf3D_Avatar",
            }}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/character.glb");
