/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import * as React, { useRef } from "solid-js";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { AnimationClip } from "three";
import { useFrame } from "solid-three";
import { useControls } from "@/leva";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.SkinnedMesh;
    Cube_1: THREE.SkinnedMesh;
    Cube_2: THREE.SkinnedMesh;
    Cube_3: THREE.SkinnedMesh;
    Body: THREE.Bone;
    IKBackLegL: THREE.Bone;
    IKFrontLegL: THREE.Bone;
    IKBackLegR: THREE.Bone;
    IKFrontLegR: THREE.Bone;
  };
  materials: {
    Main: THREE.MeshStandardMaterial;
    Nose: THREE.MeshStandardMaterial;
    Main_Light: THREE.MeshStandardMaterial;
    Eyes_Black: THREE.MeshStandardMaterial;
  };
};

type ActionName =
  | "Attack"
  | "Death"
  | "Eating"
  | "Gallop"
  | "Gallop_Jump"
  | "Idle"
  | "Idle_2"
  | "Idle_2_HeadLow"
  | "Idle_HitReact_Left"
  | "Idle_HitReact_Right"
  | "Jump_ToIdle"
  | "Walk";
interface GLTFActions extends AnimationClip {
  name: ActionName;
}

export default function WolfModel(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/animals/Wolf.gltf"
  ) as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations as any, group);

  const controls = useControls("wolf", {
    moveSpeed: 0.02,
    position: [-15, 0, 0],
    animation: {
      value: "Walk" as keyof typeof actions,
      options: Object.keys(actions) as ActionName[],
    },
  });

  React.createEffect(() => {
    actions[controls.animation]?.play();

    return () => {
      actions[controls.animation]?.stop();
    };
  }, [actions, controls.animation]);

  const [direction, setDirection] = React.useState(
    "forward" as "forward" | "backward"
  );

  function flip() {
    setDirection((b) => (b === "forward" ? "backward" : "forward"));
  }

  useFrame(() => {
    // if (group.current?.position.z ?? 0 < -3) {
    //   // flip();
    // } else if (group.current?.position.z ?? 0 > 3) {
    //   // flip();
    // }
    // group.current?.translateZ(0.03);
  });

  return (
    <group
      ref={group}
      onPointerDown={() => {
        flip();
      }}
      rotation={[0, direction === "backward" ? Math.PI : 0, 0]}
      position={controls.position}
      {...props}
      dispose={null}
    >
      <group name="Scene">
        <group name="AnimalArmature" userData={{ name: "AnimalArmature" }}>
          <primitive object={nodes.Body} />
          <primitive object={nodes.IKBackLegL} />
          <primitive object={nodes.IKFrontLegL} />
          <primitive object={nodes.IKBackLegR} />
          <primitive object={nodes.IKFrontLegR} />
          <group name="Wolf" userData={{ name: "Wolf" }}>
            <skinnedMesh
              name="Cube"
              geometry={nodes.Cube.geometry}
              material={materials.Main}
              skeleton={nodes.Cube.skeleton}
            />
            <skinnedMesh
              name="Cube_1"
              geometry={nodes.Cube_1.geometry}
              material={materials.Nose}
              skeleton={nodes.Cube_1.skeleton}
            />
            <skinnedMesh
              name="Cube_2"
              geometry={nodes.Cube_2.geometry}
              material={materials.Main_Light}
              skeleton={nodes.Cube_2.skeleton}
            />
            <skinnedMesh
              name="Cube_3"
              geometry={nodes.Cube_3.geometry}
              material={materials.Eyes_Black}
              skeleton={nodes.Cube_3.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/animals/Wolf.gltf");
