

[durable_objects]
bindings = [
  { name = "ROOM_DURABLE_OBJECT", class_name = "RoomDurableObject" },
  { name = "ROOM_HUB_DURABLE_OBJECT", class_name = "RoomHubDurableObject" }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["DurableObjectExample"] # Array of new classes

[[migrations]]
tag = "v2" # Should be unique for each entry
renamed_classes = [{from = "DurableObjectExample", to = "RoomDurableObject" }] # Array of rename directives
new_classes = ["RoomHubDurableObject"] # Array of new classes


